package com.gerardoicu.lookalike.api;

public enum ErrorCode {

	SECURITY_COOLDOWN_ACTIVE,
	SECURITY_COOKIE_TAMPERED,
	SECURITY_RATE_LIMITED,
	SECURITY_REQUEST_TOO_LARGE,
	SECURITY_TURNSTILE_INVALID,
	SECURITY_TURNSTILE_MISSING,
	SECURITY_TURNSTILE_OVERSIZED,
	SECURITY_TURNSTILE_REUSED_OR_EXPIRED,
	SECURITY_TURNSTILE_UNEXPECTED_ACTION,
	SECURITY_TURNSTILE_UNEXPECTED_HOSTNAME,
	SECURITY_TURNSTILE_UNAVAILABLE
}
