package com.gerardoicu.lookalike.api;

public enum ErrorCode {

	FACE_ANALYSIS_UNAVAILABLE,
	FACE_IMAGE_CORRUPT,
	FACE_IMAGE_DIMENSIONS_UNSUPPORTED,
	FACE_IMAGE_EMPTY,
	FACE_IMAGE_MISSING,
	FACE_IMAGE_MULTIPLE_FILES,
	FACE_IMAGE_OVERSIZED,
	FACE_IMAGE_UNSUPPORTED_FORMAT,
	FACE_MULTIPLE_USABLE_FACES,
	FACE_NO_USABLE_FACE,
	SECURITY_COOLDOWN_ACTIVE,
	SECURITY_CONFIGURATION_UNAVAILABLE,
	SECURITY_COOKIE_TAMPERED,
	SECURITY_RATE_LIMITED,
	SECURITY_REQUEST_TOO_LARGE,
	SECURITY_TURNSTILE_INVALID,
	SECURITY_TURNSTILE_MISSING,
	SECURITY_TURNSTILE_OVERSIZED,
	SECURITY_TURNSTILE_REUSED_OR_EXPIRED,
	SECURITY_TURNSTILE_UNEXPECTED_ACTION,
	SECURITY_TURNSTILE_UNEXPECTED_HOSTNAME,
	SECURITY_TURNSTILE_UNAVAILABLE
}
